Vagrant.configure("2") do |config|
  BOX_NAME = "generic/ubuntu2204"

  # Manager node
  config.vm.define "manager" do |m|
    m.vm.box = BOX_NAME
    m.vm.hostname = "manager"
    m.vm.network "private_network", ip: "192.168.56.10"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Worker 1
  config.vm.define "worker1" do |w|
    w.vm.box = BOX_NAME
    w.vm.hostname = "worker1"
    w.vm.network "private_network", ip: "192.168.56.11"
    w.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  # Worker 2
  config.vm.define "worker2" do |w|
    w.vm.box = BOX_NAME
    w.vm.hostname = "worker2"
    w.vm.network "private_network", ip: "192.168.56.12"
    w.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end
end
